### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by mikhoul** [mems/bookmarklets-context-menu#1]
I've seen your post on bugzilla and many months ago I've tried to find some way to bypass CSP for userscripts but stopped to search since I had no more time.

But I remember having discussed with others Chrome dev  and remember they told me it was possible with chrome, to bypass CSP.

Look here http://tinyurl.com/glgb3b9 at the first page of the search results, there is some interesting links and one Chrome addon that claim to work but I have no time to devote now to CSP  but maybe in few weeks/months.  :monkey: 

In meantime I will follow your progress !  :octocat: 

Regards !

**Comment by mozfreddyb** [comment]
(I'm not an expert with the WebExtension APIs, but I know a thing about CSP or two and I saw your comment on Bugzilla. I will use this issue to drive the design discussion further, as @mikhoul suggested).

* `javascript` URLs in bookmarklets tell the browser to *navigate* to a javascript URL. This is forbidden by CSP and there's nothing we can do about it, but...
* Does [`browser.tabs.executeScript()`](
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Tabs/executeScript) work in WebExtensions?
* If so, can't you take the javascript URL and turn that into a JavaScript code string, by removing the "javascript:" part and using `executeScript`?

**Comment by mikhoul** [comment]
Here some resources that can help:

- https://github.com/greasemonkey/greasemonkey/issues/2046
- https://greasyfork.org/en/forum/discussion/353/doesnt-work-because-of-content-security-policy



Regards :octocat:

**Comment by mems** [comment]
@mikhoul Thanks for resources. Chrome is less problematic than Firefox: bookmarklets are executed as non-privileged script, but ignoring the CSP, but not for its dependencies (script injection: inline or external). That means, if your bookmarklet don't have dependencies, it should be fine with Chrome.

@mozfreddyb It's possible to use `browser.tabs.executeScript()` to execute the bookmarklet source, but it's impossible to know when the user use her/his bookmarklet. There is no event for that with ([`browser.bookmarks`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks#Events). `javascript:` URIs navigate (executing the provided script to the current document), but with WebExtension API it's impossible to listen this kind of navigation event. You can listen navigation event for `ftp://`, `http(s)://`, etc. but not for `javascript:`, `data:` nor `moz-extension://`.

**Comment by mems** [comment]
Finally [I update the extension](https://addons.mozilla.org/en-US/firefox/addon/bookmarklets-context-menu/), and use the only way to execute bookmarklets with higher pivileges: a context menu that list all bookmarklets (in user's bookmarks) and execute as [content script](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts).

That means, bookmarklets (at least with Firefox) can now access to the DOM (with [Xray vision](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Xray_vision)), write to the clipboard (without require "short-lived event handler for a user action"), make cross domain requests and communicate with (others) addons on every website even with strict CSP.

Note: the CSP still applied on all subresources used by the tab's document, whatever privileges has the script append it.
Same for `eval()` and `new Function()` (in page context only)
