### ISSUE TITLE
Toolbar icon's menu is completely broken

### ISSUE THREAD

**Issue by FatOrangutan** [mems/bookmarklets-context-menu#10]
Clicking the toolbar button in v1.1.3 on Firefox 54, 55 or 56 results in the following:
![scapture](https://user-images.githubusercontent.com/8336638/28794004-7fe6656e-7652-11e7-99a7-7261c47ed6a6.PNG)
And the following error in the Browser Console:
![capture](https://user-images.githubusercontent.com/8336638/28794013-8564b8a6-7652-11e7-9266-3a9f07f72f81.PNG)
v1.1.2 works fine.

**Comment by brandizzi** [comment]
I am having the same problem. Firefox 55 @ Ubuntu.

**Comment by mems** [comment]
Thanks you
I fixed it by 358850b24c39c1b0692ee138a63f691e6f128943

**Comment by FatOrangutan** [comment]
@mems, could you push the update to addons.mozilla.org? The latest version there has been broken for more than 2 months now...

**Comment by mems** [comment]
@FatOrangutan A new version with additional commit is waiting a review, and should be available soon

**Comment by mems** [comment]
The version 1.1.4.1 has been [approved](https://addons.mozilla.org/en-US/firefox/addon/bookmarklets-context-menu/versions/?page=1#version-1.1.4.1)
