### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by nloveladyallen** [mems/bookmarklets-context-menu#13]
How do I add a bookmarklet to the context menu? I can't find any "preferences" screen to add one – the context menu and toolbar items just say "No bookmarklets found," with no option to add any.

**Comment by mems** [comment]
[Bookmarklets](https://en.wikipedia.org/wiki/Bookmarklet) are always stored as regular bookmarks.
This why bookmarklets-context-menu will get all your bookmarklets from your browser's bookmarks.

To add a bookmarklet to your bookmarks:

> "Installation" of a bookmarklet is performed by creating a new bookmark, and pasting the code into the URL destination field. Alternatively, if the bookmarklet is presented as a link, under some browsers it can be dragged and dropped onto the bookmark bar. The bookmarklet can then be run by loading the bookmark normally.
> &mdash; <cite>[Bookmarklet - Wikipedia](https://en.wikipedia.org/wiki/Bookmarklet#Installation)</cite>
