### ISSUE TITLE
bookmarklet doesn't work correctly

### ISSUE THREAD

**Issue by samuelallan72** [mems/bookmarklets-context-menu#16]
I set up this bookmarklet to open the current page in the Internet Archive:

```
javascript:location.href='https://web.archive.org/web/*/'+encodeURI(window.location)
```

It works when clicking the bookmarklet from the bookmarks menu or running in the console, but running it through this addon doesn't. Instead of navigating to the new location, it just replaces the page content with the string `https://web.archive.org/web/*/<window location>`

EDIT: discovered that it works when wrapping the code in an anonymous function - the following works with the addon:

```
javascript:(function(){location.href='https://web.archive.org/web/*/'+encodeURI(window.location);})();
```

Should this be the case? It seems that maybe this addon is parsing the javascript incorrectly?

**Comment by mems** [comment]
Fixed by 49ea6b377a88829f406ca5c4e1e349e5cceeb47c
