### ISSUE TITLE
Big Bug !

### ISSUE THREAD

**Issue by mikhoul** [mems/bookmarklets-context-menu#2]
Hi,

You uploaded the wrong package on AMO and when you try to install it it say  " the add on could not be installed because it appears to be corrupt "

I found the cause, It's caused because a faulty structure of the XPI file: http://i.imgur.com/7YQr8tJ.png

Regards !

:octocat:

**Comment by mems** [comment]
This package is a valid [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/What_are_WebExtensions). This new format [you must use](https://wiki.mozilla.org/Add-ons/developer/communication) is required for all new Firefox extensions. It's the same format as Chrome's extensions (also for Opera)

The upload package has been validated by Mozilla. They have an automatic and manual review process to ensure the package contains all requirements and doesn't have any security issues.

Once the process is validated, the distributed package on [AMO](https://addons.mozilla.org/) will contains the folder `META-INF` that correspond to Mozilla's watermark.

I don't know why you can't install this add-on. I tried on multiple machines, always with success.

What Firefox version do you use?

**Comment by mikhoul** [comment]
@mems 

I use Latest Firefox ESR 52.0.2 and have over 40 add-ons installed including webapp.

I guarantee you that the structure of your package is not valid.

AMO reviewers just review for malicious code and NOTHING else sadly, **they don't test** the addon to see if it's a valid one or not. The reason it work on your computer is because you installed it with the Firefox dev tools. 

Here's the problem and solution:,Firefox console shows : `Error: Cannot find id for add-on` 

So look here you did not put it in the "manifest.json"  Look here at a screenshot of another addon manifest beside a valid manifest: http://i.imgur.com/P080u8D.png

In meantime I just put a fake ID and your addon was installed with no problem at all since I removed all protection on my Firefox for unsigned addon.

Just add the missing part in the manifest since most casual users will not modify the manifest and remove the so called protection for unsigned addon.  😉 

Thanks for you addon ! 👍 


Regards :octocat:

**Comment by mems** [comment]
The ID is [optional from Firefox 48](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID):

> However, from Firefox 48 you can develop, debug, publish, and update WebExtensions without needing to set an explicit ID at all.
> [...]
> If the packaged add-on you upload does not contain an ID, AMO will generate one for you. It's only at this point that the add-on will be assigned a permanent ID, which will be embedded in the signed packaged add-on.

The addon ID (the backoffice of AMO provide it as "UUID") is automatically included with AMO signature (see `/META-INF/mozilla.rsa`).
If you [install the addon](https://cloud.githubusercontent.com/assets/729275/24661086/b2ede9f4-1951-11e7-9530-393f7170adfd.png) with the latest Firefox version (v52, regular release version, freshly installed), the [ID is automatically recognized](https://cloud.githubusercontent.com/assets/729275/24660174/2344434a-194f-11e7-8606-d81bae1c0369.png) without be written in `manifest.json`.

I suspect the use of `xpinstall.signatures.required = false` (only available in [ESR channel after Firefox 48](https://blog.mozilla.org/addons/2017/02/28/compatibility-for-firefox-53/#comment-223739)) disable the signature and try to read the id from `manifest.json` instead. See mozilla/addons#3350

I have added the [ID to `manifest.json`](https://github.com/mems/bookmarklets-context-menu/commit/696eb577a08cbfa75ec6a46990cb968ec2d03f02) for the next releases. That should fix this issue
