### ISSUE TITLE
Allow accessing the bookmarklets with a browser action

### ISSUE THREAD

**Issue by mikhoul** [mems/bookmarklets-context-menu#3]
Now that I have installed the addon I have a small request, could it be possible to access the bookmarklets with a toolbar button too ?

Maybe having an option to choose between the context menu and the toolbar or both. 

For me it will be lot more convenient with my workflow cause usually I put all my bookmarklets in a folders with a shortcut just below my toolbar.  🖥 

Regards :octocat:

**Comment by noamtamim** [comment]
Adding another motivation (beyond convenience): some sites block the context menu entirely. This makes the bookmarklets inaccessible. 
True, most of those sites probably don't use CSP; but once I get used to using the extension to launch bookmarklets, I'd use the extension even when CSP is not present.

**Comment by noamtamim** [comment]
@mikhoul Please change title to "Allow accessing the bookmarklets with a toolbar button".

**Comment by mems** [comment]
The v1.1 now have a browser action that allow access to bookmarklet. Usefull for pages blocks context menu
