### ISSUE TITLE
Palemoon support

### ISSUE THREAD

**Issue by hkmaly** [mems/bookmarklets-context-menu#4]
Hello,
can this extension be made to work in Palemoon? I'm not sure what is status of WebExtension in Palemoon, but it would be really useful, especially if CSP get even more prevalent.

**Comment by mikhoul** [comment]
Not really it's a WebExt,  Palemoon is limited to old Firefox addons.

Regards :octocat:

**Comment by mems** [comment]
Palemoon doesn't support Web Extensions:

> No, PM does not have support for Web Extensions. It might be possible to add someday through an extension but don't count on it.

— [About hacking extensions - Pale Moon forum](https://forum.palemoon.org/viewtopic.php?t=13655#p101346)

WebExtension have a access to low level APIs, but it's the only one system can target at the same time Firefox, Chrome, Opera and Edge.

Start Firefox 53, new extensions [must use WebExtension system](https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions)
