### ISSUE TITLE
Possible to work with this kind of bookmarklet code?

### ISSUE THREAD

**Issue by buhtig1234** [mems/bookmarklets-context-menu#6]
`javascript:void((function(d){if(self!=top||d.getElementById('toolbar')&&d.getElementById('toolbar').getAttribute('data-resizer'))return%20false;d.write('<!DOCTYPE%20HTML><html%20style="opacity:0;"><head><meta%20charset="utf-8"/></head><body><a%20data-viewport="320x480"%20data-icon="mobile">Mobile%20(e.g.%20Apple%20iPhone)</a><a%20data-viewport="320x568"%20data-icon="mobile"%20data-version="5">Apple%20iPhone%205</a><a%20data-viewport="375%C3%97667"%20data-icon="mobile"%20data-version="7">Apple%20iPhone%207</a><a%20data-viewport="414%C3%97736"%20data-icon="mobile"%20data-version="7+">Apple%20iPhone%207%20Plus</a><a%20data-viewport="600x800"%20data-icon="small-tablet">Small%20Tablet</a><a%20data-viewport="768x1024"%20data-icon="tablet">Tablet%20(e.g.%20Apple%20iPad%202-3rd,%20mini)</a><a%20data-viewport="1280x800"%20data-icon="notebook">Widescreen</a><a%20data-viewport="1920%C3%971080"%20data-icon="tv">HDTV%201080p</a><script%20src="https://lab.maltewassermann.com/viewport-resizer/resizer.min.js"></script></body></html>')})(document));`

This kind of code for the bookmarklet doesn't seem to run: it triggers a 'bookmarklet execution' promise has been rejected: Error: The operation is insecure.

Bookmarklet source: [https://lab.maltewassermann.com/viewport-resizer/](url)

Any way to get this kind of code to run?

**Comment by mems** [comment]
After changes I've made in ea9cb24b2fefa22e0331cbfc76bf89d6b84f6ae6, this bookmarklet will throw this error again.
To work again, you should change the end from `')})(document));` to `')})(wrappedJSObject.document));`.
But because it use external script injected with a script tag, this bookmarklet will not work on website with restrictive CSP

**Comment by buhtig1234** [comment]
I made the changes and it works, apart from those CSP pages you mentioned. Thanks for the help there.
